"""PDF export for credit memos using WeasyPrint."""

from src.models import CreditMemo


def render_memo_pdf(memo: CreditMemo) -> bytes:
    app = memo.application
    m = memo.risk_metrics

    conditions_html = "".join(f"<li>{c}</li>" for c in memo.conditions)

    ltv_row = ""
    if m.loan_to_value is not None:
        ltv_row = f"<tr><td>Loan-to-Value</td><td>{m.loan_to_value}x</td></tr>"

    html = f"""<!DOCTYPE html>
<html>
<head>
<style>
  @page {{ margin: 2cm; size: A4; }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; color: #1a1a2e; line-height: 1.5; }}
  .header {{ background: #1a1a2e; color: white; padding: 20px 30px; margin: -2cm -2cm 20px -2cm; }}
  .header h1 {{ margin: 0; font-size: 22pt; letter-spacing: 1px; }}
  .header .subtitle {{ color: #a0a0c0; font-size: 10pt; margin-top: 4px; }}
  .meta {{ display: flex; justify-content: space-between; margin-bottom: 20px; padding: 10px 15px; background: #f4f4f8; border-radius: 4px; font-size: 9pt; }}
  h2 {{ color: #1a1a2e; border-bottom: 2px solid #e0e0e8; padding-bottom: 4px; font-size: 13pt; margin-top: 24px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 10pt; }}
  th, td {{ padding: 6px 10px; text-align: left; border-bottom: 1px solid #e0e0e8; }}
  th {{ background: #f4f4f8; font-weight: 600; }}
  .risk-badge {{ display: inline-block; padding: 3px 12px; border-radius: 12px; font-weight: 700; font-size: 12pt; }}
  .risk-low {{ background: #d4edda; color: #155724; }}
  .risk-mid {{ background: #fff3cd; color: #856404; }}
  .risk-high {{ background: #f8d7da; color: #721c24; }}
  .section {{ margin-bottom: 10px; }}
  .conditions li {{ margin-bottom: 4px; }}
  .recommendation {{ background: #f0f4ff; padding: 12px 18px; border-left: 4px solid #1a1a2e; margin: 10px 0; font-weight: 500; }}
  .footer {{ text-align: center; font-size: 8pt; color: #888; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 8px; }}
</style>
</head>
<body>
  <div class="header">
    <h1>CREDIT MEMO</h1>
    <div class="subtitle">FinServe Financial Services — Confidential</div>
  </div>

  <div class="meta">
    <span><strong>Client:</strong> {app.client_name}</span>
    <span><strong>Product:</strong> {app.product_type.value.replace('_', ' ').title()}</span>
    <span><strong>Amount:</strong> EUR {app.requested_amount:,.0f}</span>
    <span><strong>Generated:</strong> {memo.generated_at}</span>
  </div>

  <h2>Executive Summary</h2>
  <div class="section">{memo.executive_summary}</div>

  <h2>Client Profile</h2>
  <table>
    <tr><th>Field</th><th>Detail</th></tr>
    <tr><td>Client Type</td><td>{app.client_type.value.upper()}</td></tr>
    <tr><td>Registration</td><td>{app.registration_number}</td></tr>
    <tr><td>Industry</td><td>{app.industry}</td></tr>
    <tr><td>Years in Business</td><td>{app.years_in_business}</td></tr>
    <tr><td>Employees</td><td>{app.employee_count or 'N/A'}</td></tr>
    <tr><td>Existing Client</td><td>{'Yes' if app.existing_client else 'No'}</td></tr>
  </table>

  <h2>Financial Overview</h2>
  <table>
    <tr><th>Metric</th><th>Value (EUR)</th></tr>
    <tr><td>Annual Revenue</td><td>{app.annual_revenue:,.0f}</td></tr>
    <tr><td>Net Profit</td><td>{app.net_profit:,.0f}</td></tr>
    <tr><td>Total Assets</td><td>{app.total_assets:,.0f}</td></tr>
    <tr><td>Total Liabilities</td><td>{app.total_liabilities:,.0f}</td></tr>
    <tr><td>Existing Debt</td><td>{app.existing_debt:,.0f}</td></tr>
  </table>

  <h2>Financial Analysis</h2>
  <div class="section">{memo.financial_analysis}</div>

  <h2>Risk Metrics</h2>
  <table>
    <tr><th>Ratio</th><th>Value</th></tr>
    <tr><td>Debt-to-Equity</td><td>{m.debt_to_equity}x</td></tr>
    <tr><td>Debt Service Coverage (DSCR)</td><td>{m.debt_service_coverage}x</td></tr>
    <tr><td>Current Ratio</td><td>{m.current_ratio}x</td></tr>
    <tr><td>Leverage Ratio</td><td>{m.leverage_ratio}x</td></tr>
    {ltv_row}
    <tr><td>Revenue-to-Debt Ratio</td><td>{m.revenue_to_debt}x</td></tr>
    <tr><td>Risk Score</td><td>{m.risk_score} / 100</td></tr>
    <tr><td>Risk Rating</td><td>
      <span class="risk-badge {'risk-low' if m.risk_score <= 35 else 'risk-mid' if m.risk_score <= 65 else 'risk-high'}">{m.risk_rating}</span>
    </td></tr>
  </table>

  <h2>Risk Assessment</h2>
  <div class="section">{memo.risk_assessment}</div>

  <h2>Collateral Analysis</h2>
  <div class="section">{memo.collateral_analysis}</div>

  <h2>Recommendation</h2>
  <div class="recommendation">{memo.recommendation}</div>

  <h2>Conditions & Covenants</h2>
  <ol class="conditions">{conditions_html}</ol>

  <div class="footer">
    Generated by FinServe AI Credit Memo Generator — for internal use only — {memo.generated_at}
  </div>
</body>
</html>"""

    from weasyprint import HTML
    return HTML(string=html).write_pdf()
